version: '2'
services:
  web:
    build: .
    ports:
     - "5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  redis:
    image: redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"